version: "3.0"

services:
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - BASE_URL=/ombi
    volumes:
      -  ./data/config:/config