version: "3.0"

services:
  homer:
    image: b4bz/homer:latest
    restart: always
    container_name: homer-dashboard
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./data/assets:/www/assets
    ports:
      - "8080:8080"