version: "3.0"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - ./data/config:/config
      - ./data/movies:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web, websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.example.com`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=production"
    networks:
      - web

networks:
  web:
    external: true