version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./src:/var/www
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=mysqldatabase
      - MYSQL_USER=mysqlusername
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_ROOT_PASSWORD=mysql_root_password
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"