version: '3'

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    